# Generated by Django 5.1.3 on 2024-11-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
